[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_pgsql", "php82Extensions.pgsql", "php82Extensions.mbstring", "php82Extensions.gd", "nodejs_18"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci", "npm run build"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
